apiRules:
- include:
    uidRegex: ^DocFxForUnity
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- include:
    uidRegex: ^A3.*
    type: Namespace
- include:
    uidRegex: ^Agate.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace